-- group_commands.lua -- Group of most minimally-invasive and useful commands

load "command_admin"
load "command_an"
load "command_caps"
load "command_cli"
load "command_cmds"
load "command_exec"
load "command_fog"
load "command_ignore"
load "command_kick"
load "command_kill"
load "command_modutils"
load "command_ping"
load "command_pm"
load "command_ratio"
load "command_say"
load "command_secspec"
load "command_server"
load "command_switch"
load "command_tp"
load "command_ups"
load "command_version"
load "command_who"
-- TODO: these *really* seem out of place. . .
load "god"
load "jp"
load "noclip"
